apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gksmmf031/rakuraku:132
        env:
        - name: RDS_HOST
          value: "{{ awssecretsmanager.secret.backend.rds_host }}"
        - name: RDS_USER
          value: "{{ awssecretsmanager.secret.backend.rds_user }}"
        - name: RDS_PASSWORD
          value: "{{ awssecretsmanager.secret.backend.rds_password }}"
        - name: MONGO_HOST
          value: "{{ awssecretsmanager.secret.backend.mongo_host }}"
        - name: MONGO_USER
          value: "{{ awssecretsmanager.secret.backend.mongo_user }}"
        - name: MONGO_PASSWORD
          value: "{{ awssecretsmanager.secret.backend.mongo_password }}"
        - name: JWT_SECRET
          value: "{{ awssecretsmanager.secret.backend.jwt_secret }}"

