apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: argocd
spec:
  replicas: 2
  selector: # 필수 필드 추가
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gksmmf031/rakuraku:17
        env:
        - name: RDS_HOST
          value: "{{ awssecretsmanager.secret['/secret/backend'].rds_host }}"
        - name: RDS_USER
          value: "{{ awssecretsmanager.secret['/secret/backend'].rds_user }}"
        - name: RDS_PASSWORD
          value: "{{ awssecretsmanager.secret['/secret/backend'].rds_password }}"
        - name: MONGO_HOST
          value: "{{ awssecretsmanager.secret['/secret/backend'].mongo_host }}"
        - name: MONGO_USER
          value: "{{ awssecretsmanager.secret['/secret/backend'].mongo_user }}"
        - name: MONGO_PASSWORD
          value: "{{ awssecretsmanager.secret['/secret/backend'].mongo_password }}"
        - name: JWT_SECRET
          value: "{{ awssecretsmanager.secret['/secret/backend'].jwt_secret }}"

