apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: argocd  # 네임스페이스 확인! (필요하면 수정)
  labels:
    app: backend
spec:
  replicas: 2  # 실행할 백엔드 Pod 개수 (필요에 따라 조정)
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gksmmf031/rakuraku:40
          ports:
            - containerPort: 8080  # Spring Boot 기본 포트 (application.properties에 맞춰야 함)
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          volumeMounts:
            - name: ssh-key-volume
              mountPath: /root/.ssh
              readOnly: true
      volumes:
        - name: ssh-key-volume
          secret:
            secretName: mongo-ssh-key

