apiVersion: apps/v1
kind: Deployment
metadata:
  name: rakuraku-deploy
  namespace: argocd  # service와 같은 네임스페이스로 설정
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rakuraku
  template:
    metadata:
      labels:
        app: rakuraku
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - cicd
      containers:
      - name: rakuraku
        image: gksmmf031/rakuraku:126
        ports:
        - containerPort: 4000  # service.yaml과 일치
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: MONGO_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_HOST
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET

