apiVersion: apps/v1
kind: Deployment
metadata:
  name: rakuraku-deploy
  namespace: argocd  # service와 같은 네임스페이스로 설정
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rakuraku
  template:
    metadata:
      labels:
        app: rakuraku
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - cicd
      containers:
      - name: rakuraku
        image: gksmmf031/rakuraku:62a5cd8-114
        ports:
        - containerPort: 4000  # service.yaml과 일치

