apiVersion: apps/v1
kind: Deployment
metadata:
  name: rakuraku-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: rakuraku
  template:
    metadata:
      labels:
        run: rakuraku
    spec:
      containers:
      - name: rakuraku
        image: gksmmf031/rakuraku:latest  # Docker Hub에 푸시된 실제 이미지 이름과 태그
        ports:
        - containerPort: 80

