apiVersion: apps/v1
kind: Deployment
metadata:
  name: rakuraku-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: rakuraku
  template:
    metadata:
      labels:
        run: rakuraku
    spec:
      containers:
      - name: rakuraku
        image: gksmmf031/rakuraku:latest  # Docker Hub 이미지 이름
        ports:
        - containerPort: 3000  # 애플리케이션 내부에서 사용하는 포트

