apiVersion: v1
kind: Service
metadata:
  name: rakuraku-svc
  namespace: argocd
spec:
  selector:
    app: rakuraku  # Deployment의 matchLabels와 동일해야 함
  ports:
  - protocol: TCP
    port: 4000      # LoadBalancer가 외부에서 연결할 포트
    targetPort: 4000  # Pod 내부 컨테이너 포트와 일치해야 함
  type: LoadBalancer

