apiVersion: v1
kind: Service
metadata:
  name: rakuraku-svc
spec:
  selector:
    run: rakuraku  # deployment.yaml의 labels와 일치
  ports:
  - port: 80
    targetPort: 80  # deployment.yaml의 containerPort와 일치
  type: LoadBalancer

