apiVersion: v1
kind: Service
metadata:
  name: rakuraku-svc
  namespace: argocd
spec:
  selector:
    app: backend  # Deployment의 matchLabels와 동일해야 함
  ports:
  - protocol: TCP
    port: 4000      # 외부 접근 포트
    targetPort: 8085  # 컨테이너 내부 애플리케이션 포트
  type: LoadBalancer
