name: Update Kubernetes Manifests

on:
  push:
    branches:
      - main

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 새 이미지 태그 업데이트
    - name: Update Kubernetes Manifests
      run: |
        # 새 Docker 이미지 태그
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        
        # 매니페스트 파일 업데이트
        sed -i "s|image: .*/backend-app:.*|image: gksmmf031/backend-app:$IMAGE_TAG|g" k8s/deployment.yaml

    # 3. 변경 사항 커밋 및 푸시
    - name: Commit and Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add k8s/deployment.yaml
        git commit -m "Updated image tag to $IMAGE_TAG"
        git push

